name: Google-cloud and GKE authentication
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v3'
      with:
        service_account: 'terraform-test-deployment@nabuminds-test.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/563370139005/locations/global/workloadIdentityPools/bitbucket/providers/repository'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure kubectl
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --region ${{ env.GKE_REGION }} \
          --project ${{ env.PROJECT_ID }}


    - name: Create namespace if not exists
      run: |
        kubectl create namespace ${{ env.GKE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -