apiVersion: v1
kind: Service
metadata:
  name: snake-game-backend
  labels:
    app: snake-game
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: snake-game
    component: backend

